apiVersion: v1
kind: Service
metadata:
  labels:
    app: thrasher
  name: thrasher
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: thrasher
  type: LoadBalancer
